export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function Expenses({
  children,
}: {
  children: React.ReactNode
}) {
  return (<div>expenses</div>)
}
