version: '3.8'

services:
  mongo:
    image: nertworkweb/mongodb-no-avx
    container_name: 'test-mongo'
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  app:
    image: rustback
    build:
      context: .
      dockerfile: ./RustStore/Dockerfile
    ports:
      - "7208:7208"