version: '3.8'

services:
  mongodb:
    #image: nertworkweb/mongodb-no-avx
    image: mongo:4.4
    container_name: 'test-mongo'
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  app:
    image: rustback
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: RustStore/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - mongodb
    env_file:
      - .env.prod