version: '3.8'

services:
  mongodb:
    #image: nertworkweb/mongodb-no-avx
    image: mongo:4.4
    container_name: 'ruststore-mongodb'
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  app:
    image: rustback
    container_name: 'ruststore-app'
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    build:
      context: .
      dockerfile: RustStore/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - mongodb
    env_file:
      - RustStore/.env.prod
    volumes:
      - C:\rust-store-storage\images:/images

  redis:
    image: redis
    container_name: 'ruststore-redis'
    ports:
      - "6379:6379"