import { PromoCodes } from "../../_components/Promocodes"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function PromoCodePage() {
  return (<div>
    <PromoCodes />
  </div>)
}
