
import { AuthCheck } from '@/AdminComponents/AuthCheck/AuthCheck';
import './styled.css'
import { WorkLayout } from '@/components/WorkLayout/WorkLayout';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AuthCheck>
          <WorkLayout>
            {children}
          </WorkLayout>
        </AuthCheck>
        </body>
    </html>
  )
}
