
import { AuthCheck } from '@/AdminComponents/AuthCheck/AuthCheck';
import './styled.css'
import { WorkLayout } from '@/components/WorkLayout/WorkLayout';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const Links = [
  {
    href: '/work/reports',
    title: 'Репорты'
  },
  {
    href: '/work/bans',
    title: 'Баны'
  },
]


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AuthCheck>
          <WorkLayout links={Links}>
            {children}
          </WorkLayout>
        </AuthCheck>
        </body>
    </html>
  )
}
