import '@mantine/core/styles.css';
import '@mantine/charts/styles.css';
import { theme } from "@/components/theme/theme"
import { MantineProvider } from "@mantine/core"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <MantineProvider theme={theme}>
          {children}
        </MantineProvider>
        </body>
    </html>
  )
}
