import '@mantine/core/styles.css';
import '@mantine/charts/styles.css';
import '@mantine/dates/styles.css';
import { theme } from "@/components/theme/theme"
import { MantineProvider } from "@mantine/core"
import { AppShellWrapper } from '@/components/AppShell';
import { AuthCheck } from '@/AdminComponents/AuthCheck/AuthCheck';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <MantineProvider theme={theme}>
          <AppShellWrapper>
            <AuthCheck>
              {children}
            </AuthCheck>
           
          </AppShellWrapper>
        </MantineProvider>
        </body>
    </html>
  )
}
