import '@mantine/core/styles.css';
import '@mantine/charts/styles.css';
import '@mantine/dates/styles.css';
import { theme } from "@/components/theme/theme"
import { MantineProvider } from "@mantine/core"
import { AuthCheck } from '@/AdminComponents/AuthCheck/AuthCheck';
import { WorkLayout } from '@/components/WorkLayout/WorkLayout';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const links = [
  {
    href: '/admin',
    title: 'Главная'
  },
  {
    href: '/admin/profile',
    title: 'Профиль'
  },
  {
    href: '/admin/findserver',
    title: 'Поиск серверов'
  },
  {
    href: '/admin/purchases',
    subtitle: 'Статистика',
    title: 'Покупки'
  },
  {
    href: '/admin/profit',
    title: 'Пополнения'
  },
  {
    href: '/admin/expenses',
    title: 'Расходы'
  },
  {
    href: '/admin/sharedsettings',
    subtitle: 'Общие',
    title: 'Настройки'
  },
  {
    href: '/admin/products',
    title: 'Товары'
  },
  {
    href: '/admin/promocodes',
    title: 'Промокоды'
  },
  {
    href: '/admin/players',
    subtitle: 'Сервер',
    title: 'Игроки'
  },
]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <MantineProvider theme={theme}>
        <AuthCheck>
          <WorkLayout links={links}>
            {children}
          </WorkLayout>
        </AuthCheck>
        </MantineProvider>
        </body>
    </html>
  )
}
