import { Products } from "../../_components/Products"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function ProductsPage({
  children,
}: {
  children: React.ReactNode
}) {
  return (<div>
    <Products />
  </div>)
}
