export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function Products({
  children,
}: {
  children: React.ReactNode
}) {
  return (<div>products</div>)
}
