import { PageTitle } from "../../_components/PageTitle"
import { Stats } from "./_stats"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function purchases({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>
      <Stats /></div>
)
}
