import '@mantine/core/styles.css';
import type { Metadata } from 'next'

import { Inter } from 'next/font/google'
import './globals.css'
import styles from './page.module.css'
import { MantineProvider } from '@mantine/core';
import { theme } from '@/components/theme/theme';
import { NavBar } from '@/components/NavBar';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.background}>
          <MantineProvider theme={theme}>
            <nav className={styles.nav}>
              <NavBar />
            </nav>
          </MantineProvider>
          <main>
            <MantineProvider theme={theme}>
              {children}
            </MantineProvider>
          </main>
         </div>
        </body>
    </html>
  )
}
