export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  }
  
  export default function Player({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (<div>Player</div>)
  }
  