name: Publick Docker


on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubunto-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registery
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          registry: docker.pkg.github.com
          name: docker.pkg.github.com/famus0v/rust-store
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "develop"